name: CI Kanban API

on:
  push:
    branches:
      - master

jobs:
  build_e_testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Mostrar estrutura
        run: |
          pwd
          ls -R

      - name: Build Maven
        run: mvn clean package -f pom.xml